### ISSUE TITLE
Ecran noir au lancement.

### ISSUE THREAD

**Issue by Illynir** [orian34/meakashi#7]
Hello,

Pris d'une folie de me refaire ce VN, j'ai installé les 8 chapitres (que j'ai sur GOG) et installé les mod 07th sans problème avec l'installateur automatique + le patch FR.

Malheureusement le patch FR ne fonctionne pas sur ce chapitre (il fonctionne sur tous les autres), le jeu reste bloqué sur un écran noir au lancement, indéfiniment. J'ai bien entendu essayé sans le patch FR et le jeu moddé fonctionne normalement en anglais. J'ai également essayé d'installé le patch FR disponible ici manuellement mais le problème est identique.

Voila, juste pour vous informer de ce problème, à moins qu'il soit connu ou qu'il y a une astuce que je n'ai pas trouvé.

Merci pour le boulot en tout cas. :)

**Comment by orian34** [comment]
Je vais essayer de voir si il y a un problème. Une update devrait pas tarder pour novembre

**Comment by orian34** [comment]
The problem was found, you need to install the assets file manually until we can fix it.

**Comment by Illynir** [comment]
I don't know whether to write in English or French here so I put both:

**Anglais:** 

I just tried it and I managed to make it work. The automatic installation via the installer doesn't work because it doesn't modify the correct sharedasset. But when I try to manually install the FR patch and modify the sharedasset file, the game remains in English except for the menus.

The only way I've found to make it work is to install the FR patch with the installer and then manually modify the sharedasset file myself, and now it works and the game is in French.

Everything seems to work now except the menu on the title screen whose words are cut and change when you move the mouse over it, not a big problem though but it's worth noting.

**Français:**

Je viens d'essayer et j'ai réussi à le faire fonctionner. L'installation automatique via l'installer ne fonctionne pas car il ne modifie en effet pas le bon sharedasset. Mais quand j'essaye d'installer manuellement le patch FR et que je modifie le fichier sharedasset le jeu reste en anglais excepté les menus.

La seule façon que j'ai trouvé de le faire fonctionner est d'installer avec l'installateur le patch Fr puis de modifier moi même manuellement le fichier sharedasset, et maintenant ça fonctionne et le jeu est en français.

Tout à l'air de fonctionner maintenant à part le menu sur l'écran titre dont les mots sont coupés et change quand on passe la souris dessus, pas un gros problème cela dit mais c'est à noter.

**Comment by drojf** [comment]
@Illynir hi, i'm not sure if you're the same person on discord, but can you send the install log?

If you're the same person from discord, it should be `MOD-INSTALLER-LOG-2020-11-03_00-22-38.txt`

Just now I did an install with the latest installer on Ubuntu, Steam, of meakashi, with the language patch, and it correctly selected the language patch LinuxMac-Steam-5.5.3p3.assets , so I'm wondering what happened

**Comment by drojf** [comment]
I did possibly fix a bug on the latest installer about 5 days ago with the sharedasset installation, but I think on discord you said you got the installer about 3 days ago - if I have the install log I can check which version you used to install. The latest is "v1.1.67"

**Comment by Illynir** [comment]
Hello, I sent you the file on Discord, it wasn't me you saw because I just arrived on Discord just now.

I'm going to try different things and update the installer, it's dated October 26th.

**Comment by Illynir** [comment]
Ok, I just tried with the last installer and the installation of the FR patch works correctly now. thank you. :)

I put here two screenshot for the menu problem to be complete but I think it's just a bug of the FR patch only:

Menu:
![Sans titre](https://user-images.githubusercontent.com/22648460/98491072-f2603580-2233-11eb-9bac-0ee3a285e6ff.jpg)

Menu with mouse over:
![Sans titre1](https://user-images.githubusercontent.com/22648460/98491090-0441d880-2234-11eb-922e-c5bf419b5325.jpg)

Thank you all for the work :)
